import React, { Component } from "react";
import { View } from "react-native";
import Styles from "./Styles";
import AnimatedList from "./AnimatedList";

const DATA = [
  {
    original_name: "Game of Thrones",
    id: 1399,
    name: "Game of Thrones",
    vote_count: 2855,
    vote_average: 8.05,
    poster_path: "/gwPSoYUHAKmdyVywgLpKKA4BjRr.jpg",
    first_air_date: "2011-04-17",
    popularity: 121.99699,
    genre_ids: [10765, 18, 10759],
    original_language: "en",
    backdrop_path: "/mUkuc2wyV9dHLG0D0Loaw5pO2s8.jpg",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    origin_country: ["US"],
  },
  {
    original_name: "The Walking Dead",
    id: 1402,
    name: "The Walking Dead",
    vote_count: 2240,
    vote_average: 7.38,
    poster_path: "/vxuoMW6YBt6UsxvMfRNwRl9LtWS.jpg",
    first_air_date: "2010-10-31",
    popularity: 53.689595,
    genre_ids: [10759, 18],
    original_language: "en",
    backdrop_path: "/h1qyblc5p9G3ZWIVK8ZrkpxcXgO.jpg",
    overview:
      "Sheriff's deputy Rick Grimes awakens from a coma to find a post-apocalyptic world dominated by flesh-eating zombies. He sets out to find his family and encounters many other survivors along the way.",
    origin_country: ["US"],
  },
  {
    original_name: "The Simpsons",
    id: 456,
    name: "The Simpsons",
    vote_count: 947,
    vote_average: 7.1,
    poster_path: "/yTZQkSsxUFJZJe67IenRM0AEklc.jpg",
    first_air_date: "1989-12-17",
    popularity: 39.962865,
    genre_ids: [16, 35],
    original_language: "en",
    backdrop_path: "/f5uNbUC76oowt5mt5J9QlqrIYQ6.jpg",
    overview:
      "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
    origin_country: ["US"],
  },
  {
    original_name: "Doctor Who",
    id: 57243,
    name: "Doctor Who",
    vote_count: 820,
    vote_average: 6.92,
    poster_path: "/cFcZYgPRFZdBkA7EsxHz5Cb8x5.jpg",
    first_air_date: "2005-03-26",
    popularity: 38.951272,
    genre_ids: [10759, 18, 10765],
    original_language: "en",
    backdrop_path: "/tQkigP2fItdzJWvtIhBvHxgs5yE.jpg",
    overview:
      "The Doctor looks and seems human. He's handsome, witty, and could be mistaken for just another man in the street. But he is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living – more of a hobby actually, and he's very, very good at it. He's saved us from alien menaces and evil from before time began – but just who is he?",
    origin_country: ["GB"],
  },
  {
    original_name: "Twin Peaks",
    id: 1920,
    name: "Twin Peaks",
    vote_count: 375,
    vote_average: 8.03,
    poster_path: "/6W6zWBAay6XVBgJsOu6c2mlFZ8l.jpg",
    first_air_date: "1990-04-08",
    popularity: 38.625578,
    genre_ids: [18, 9648, 53],
    original_language: "en",
    backdrop_path: "/3Y91NnZZyTS8UbgJUw3AZ6WWKTN.jpg",
    overview:
      "The body of Laura Palmer is washed up on a beach near the small Washington state town of Twin Peaks. FBI Special Agent Dale Cooper is called in to investigate her strange demise only to uncover a web of mystery that ultimately leads him deep into the heart of the surrounding woodland and his very own soul.",
    origin_country: ["US"],
  },
  {
    original_name: "The Big Bang Theory",
    id: 1418,
    name: "The Big Bang Theory",
    vote_count: 1761,
    vote_average: 6.97,
    poster_path: "/wQoosZYg9FqPrmI4zeCLRdEbqAB.jpg",
    first_air_date: "2007-09-24",
    popularity: 37.484863,
    genre_ids: [35],
    original_language: "en",
    backdrop_path: "/nGsNruW3W27V6r4gkyc3iiEGsKR.jpg",
    overview:
      "The Big Bang Theory is centered on five characters living in Pasadena, California: roommates Leonard Hofstadter and Sheldon Cooper; Penny, a waitress and aspiring actress who lives across the hall; and Leonard and Sheldon's equally geeky and socially awkward friends and co-workers, mechanical engineer Howard Wolowitz and astrophysicist Raj Koothrappali. The geekiness and intellect of the four guys is contrasted for comic effect with Penny's social skills and common sense.",
    origin_country: ["US"],
  },
  {
    original_name: "Suits",
    id: 37680,
    name: "Suits",
    vote_count: 425,
    vote_average: 7.42,
    poster_path: "/i6Iu6pTzfL6iRWhXuYkNs8cPdJF.jpg",
    first_air_date: "2011-06-23",
    popularity: 36.314005,
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/iU2cObod4GoHAcgrc5AtfwIVizL.jpg",
    overview:
      "While running from a drug deal gone bad, Mike Ross, a brilliant young college-dropout, slips into a job interview with one of New York City's best legal closers, Harvey Specter. Tired of cookie-cutter law school grads, Harvey takes a gamble by hiring Mike on the spot after he recognizes his raw talent and photographic memory. Mike and Harvey are a winning team. Even though Mike is a genius, he still has a lot to learn about law. And while Harvey may seem like an emotionless, cold-blooded shark, Mike's sympathy and concern for their cases and clients will help remind Harvey why he went into law in the first place. Mike's other allies in the office include the firm's best paralegal Rachel and Harvey's no-nonsense assistant Donna to help him serve justice. Proving to be an irrepressible duo and invaluable to the practice, Mike and Harvey must keep their secret from everyone including managing partner Jessica and Harvey's arch nemesis Louis, who seems intent on making Mike's life as difficult as possible.",
    origin_country: ["US"],
  },
  {
    original_name: "Breaking Bad",
    id: 1396,
    name: "Breaking Bad",
    vote_count: 1705,
    vote_average: 8.17,
    poster_path: "/1yeVJox3rjo2jBKrrihIMj7uoS9.jpg",
    first_air_date: "2008-01-19",
    popularity: 32.928408,
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/hbgPoI0GBrXJfGjYNV2fMQU0xou.jpg",
    overview:
      "Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. Set and produced in Albuquerque, New Mexico, Breaking Bad is the story of Walter White, a struggling high school chemistry teacher who is diagnosed with inoperable lung cancer at the beginning of the series. He turns to a life of crime, producing and selling methamphetamine, in order to secure his family's financial future before he dies, teaming with his former student, Jesse Pinkman. Heavily serialized, the series is known for positioning its characters in seemingly inextricable corners and has been labeled a contemporary western by its creator.",
    origin_country: ["US"],
  },
  {
    original_name: "The Flash",
    id: 60735,
    name: "The Flash",
    vote_count: 1370,
    vote_average: 6.8,
    poster_path: "/lUFK7ElGCk9kVEryDJHICeNdmd1.jpg",
    first_air_date: "2014-10-07",
    popularity: 31.561375,
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/mmxxEpTqVdwBlu5Pii7tbedBkPC.jpg",
    overview:
      'After a particle accelerator causes a freak storm, CSI Investigator Barry Allen is struck by lightning and falls into a coma. Months later he awakens with the power of super speed, granting him the ability to move through Central City like an unseen guardian angel. Though initially excited by his newfound powers, Barry is shocked to discover he is not the only "meta-human" who was created in the wake of the accelerator explosion -- and not everyone is using their new powers for good. Barry partners with S.T.A.R. Labs and dedicates his life to protect the innocent. For now, only a few close friends and associates know that Barry is literally the fastest man alive, but it won\'t be long before the world learns what Barry Allen has become...The Flash.',
    origin_country: ["US"],
  },
  {
    original_name: "Arrow",
    id: 1412,
    name: "Arrow",
    vote_count: 1140,
    vote_average: 6.13,
    poster_path: "/mo0FP1GxOFZT4UDde7RFDz5APXF.jpg",
    first_air_date: "2012-10-10",
    popularity: 30.973948,
    genre_ids: [28, 12, 80, 18, 9648, 878],
    original_language: "en",
    backdrop_path: "/dKxkwAJfGuznW8Hu0mhaDJtna0n.jpg",
    overview:
      "Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.",
    origin_country: ["US"],
  },
  {
    original_name: "Supernatural",
    id: 1622,
    name: "Supernatural",
    vote_count: 959,
    vote_average: 7.07,
    poster_path: "/3iFm6Kz7iYoFaEcj4fLyZHAmTQA.jpg",
    first_air_date: "2005-09-13",
    popularity: 30.51316,
    genre_ids: [18, 9648, 10765],
    original_language: "en",
    backdrop_path: "/koMUCyGWNtH5LXYbGqjsUwvgtsT.jpg",
    overview:
      "When they were boys, Sam and Dean Winchester lost their mother to a mysterious and demonic supernatural force. Subsequently, their father raised them to be soldiers. He taught them about the paranormal evil that lives in the dark corners and on the back roads of America ... and he taught them how to kill it. Now, the Winchester brothers crisscross the country in their '67 Chevy Impala, battling every kind of supernatural threat they encounter along the way. ",
    origin_country: ["US"],
  },
  {
    original_name: "The Mist",
    id: 68315,
    name: "The Mist",
    vote_count: 47,
    vote_average: 5.49,
    poster_path: "/iwDmsffJ5qYBxiGTPdwgIKTscKu.jpg",
    first_air_date: "2017-06-22",
    popularity: 29.145903,
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/scITaEMqkmQqBONRneKy8QjZlKb.jpg",
    overview:
      "A small town family is torn apart by a brutal crime. As they deal with the fallout an eerie mist rolls in, suddenly cutting them off from the rest of the world, and in some cases, each other.",
    origin_country: ["US"],
  },
  {
    original_name: "Grey's Anatomy",
    id: 1416,
    name: "Grey's Anatomy",
    vote_count: 428,
    vote_average: 6.02,
    poster_path: "/aI4bobthe7OORg4s2zjm0f0FdC1.jpg",
    first_air_date: "2005-03-27",
    popularity: 29.06084,
    genre_ids: [18],
    original_language: "en",
    backdrop_path: "/rIu4XdgSV50B6nhgUuEPuufHsB2.jpg",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    origin_country: ["US"],
  },
  {
    original_name: "Marvel's Daredevil",
    id: 61889,
    name: "Marvel's Daredevil",
    vote_count: 694,
    vote_average: 7.57,
    poster_path: "/cidOqJL8tayqvv3TpfTQCsgeITu.jpg",
    first_air_date: "2015-04-10",
    popularity: 28.001132,
    genre_ids: [28, 80],
    original_language: "en",
    backdrop_path: "/dpNeXLEnuKzAvbNwveJhNEiQvXZ.jpg",
    overview:
      "Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.",
    origin_country: ["US"],
  },
  {
    original_name: "Once Upon a Time",
    id: 39272,
    name: "Once Upon a Time",
    vote_count: 412,
    vote_average: 6.44,
    poster_path: "/wBfEtXcnXtw5VJwChYU82CG6Att.jpg",
    first_air_date: "2011-10-23",
    popularity: 27.345346,
    genre_ids: [18, 10765],
    original_language: "en",
    backdrop_path: "/Otzq1sny6BAuvZdAO1EMdUkDUc.jpg",
    overview:
      "There is a town in Maine where every story book character you've ever known is trapped between two worlds, victims of a powerful curse. Only one knows the truth and only one can break the spell.\n\nEmma Swan is a 28-year-old bail bonds collector who has been supporting herself since she was abandoned as a baby. Things change for her when her son Henry, whom she abandoned years ago, finds her and asks for her help explaining that she is from a different world where she is Snow White's missing daughter.",
    origin_country: ["US"],
  },
  {
    original_name: "Pretty Little Liars",
    id: 31917,
    name: "Pretty Little Liars",
    vote_count: 301,
    vote_average: 6.05,
    poster_path: "/aUPbHiLS3hCHKjtLsncFa9g0viV.jpg",
    first_air_date: "2010-06-08",
    popularity: 26.030811,
    genre_ids: [18, 9648],
    original_language: "en",
    backdrop_path: "/rQGBjWNveVeF8f2PGRtS85w9o9r.jpg",
    overview:
      'Based on the Pretty Little Liars series of young adult novels by Sara Shepard, the series follows the lives of four girls — Spencer, Hanna, Aria, and Emily — whose clique falls apart after the disappearance of their queen bee, Alison. One year later, they begin receiving messages from someone using the name "A" who threatens to expose their secrets — including long-hidden ones they thought only Alison knew.',
    origin_country: ["US"],
  },
  {
    original_name: "Cops",
    id: 3670,
    name: "Cops",
    vote_count: 52,
    vote_average: 5.7,
    poster_path: "/zZy2Eg2ioxRgWc9WjMIu67ueT97.jpg",
    first_air_date: "1989-03-11",
    popularity: 25.088506,
    genre_ids: [10764],
    original_language: "en",
    backdrop_path: "/7xQR6ixywZofrEHKfI1z6CWKFsC.jpg",
    overview:
      "Follow real-life law enforcement officers from various regions and departments of the United States armed with nothing but with cameras to capture their actions, performing their daily duty to serve and protect the public.",
    origin_country: ["US"],
  },
  {
    original_name: "Family Guy",
    id: 1434,
    name: "Family Guy",
    vote_count: 668,
    vote_average: 6.64,
    poster_path: "/gBGUL1UTUNmdRQT8gA1LUV4yg39.jpg",
    first_air_date: "1999-01-31",
    popularity: 25.02612,
    genre_ids: [16, 35],
    original_language: "en",
    backdrop_path: "/pH38r4TWTqq7Mcs6XAlwgzNUeJe.jpg",
    overview:
      "Sick, twisted, politically incorrect and Freakin' Sweet animated series featuring the adventures of the dysfunctional Griffin family. Bumbling Peter and long-suffering Lois have three kids. Stewie (a brilliant but sadistic baby bent on killing his mother and taking over the world), Meg (the oldest, and is the most unpopular girl in town) and Chris (the middle kid, he's not very bright but has a passion for movies). The final member of the family is Brian - a talking dog and much more than a pet, he keeps Stewie in check whilst sipping Martinis and sorting through his own life issues.",
    origin_country: ["US"],
  },
  {
    original_name: "Prison Break",
    id: 2288,
    name: "Prison Break",
    vote_count: 614,
    vote_average: 7.45,
    poster_path: "/5E1BhkCgjLBlqx557Z5yzcN0i88.jpg",
    first_air_date: "2005-08-29",
    popularity: 24.1668,
    genre_ids: [10759, 80, 18, 9648],
    original_language: "en",
    backdrop_path: "/92OPBZpLc82y8CzOtrQ8P9RDvIN.jpg",
    overview:
      "Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out, from the inside out.",
    origin_country: ["US"],
  },
  {
    original_name: "Friends",
    id: 1668,
    name: "Friends",
    vote_count: 735,
    vote_average: 7.76,
    poster_path: "/7buCWBTpiPrCF5Lt023dSC60rgS.jpg",
    first_air_date: "1994-09-22",
    popularity: 23.045334,
    genre_ids: [35],
    original_language: "en",
    backdrop_path: "/efiX8iir6GEBWCD0uCFIi5NAyYA.jpg",
    overview:
      "Friends is an American sitcom revolving around a group of friends in the New York City borough of Manhattan. Episodes typically depict the friends' comedic and romantic adventures and career issues, such as Joey auditioning for roles or Rachel seeking jobs in the fashion industry. The six characters each have many dates and serious relationships, such as Monica with Richard Burke and Ross with Emily Waltham. Other frequently recurring characters include Ross and Monica's parents in Long Island, Ross's ex-wife and their son, Central Perk barista Gunther, Chandler's ex-girlfriend Janice, and Phoebe's twin sister Ursula.",
    origin_country: ["US"],
  },
];

export default class ReactNativeAnimatedList extends Component {
  render() {
    return (
      <View style={Styles.App.container}>
        <AnimatedList data={DATA} />
      </View>
    );
  }
}
