export default {
  electric: "ELECTRIC",
  acoustic: "ACOUSTIC",
  bass: "BASS",
  daily: "DAILY",
  somedays: "SOMEDAYS",
  weekly: "WEEKLY",
  addGuitar: "ADD_GUITAR",
  editGuitar: "EDIT_GUITAR",
  showNotifications: "SHOW_NOTIFICATIONS",
  selectedGuitar: "SELECTED_GUITAR",
  changeAge: "CHANGE_AGE",
  deleteGuitar: "DELETE_GUITAR",
  persistedNotifications: "PERSISTED_NOTIFICATIONS",
  persistedGuitars: "PERSISTED_GUITARS",
  persistedTheme: "PERSISTED_THEME",
  initializeGuitars: "INITIALIZE_GUITARS",
  toggleNightShade: "TOGGLE_NIGHT_SHADE",
  initializeTheme: "INITIALIZE_THEME"
};
